name: Publish Docker Images

on:
  push:
    branches: ['main']

jobs:
  # For creating angular image
  push_angular_image:
    name: Push Angular Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Angular image
        id: angular-meta
        uses: docker/metadata-action@v5
        with:
          images: changco0987/managementsys-angular-view

      - name: Build and push Angular Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./angular-view
          file: ./angular-view/Dockerfile
          push: true
          tags: ${{ steps.angular-meta.outputs.tags }}
          labels: ${{ steps.angular-meta.outputs.labels }}

  # For creating laravel image
  push_laravel_image:
    name: Push Laravel Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Laravel image
        id: laravel-meta
        uses: docker/metadata-action@v5
        with:
          images: changco0987/managementsys-laravel-api

      - name: Build and push Laravel Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./laravel-api
          file: ./laravel-api/Dockerfile
          push: true
          tags: ${{ steps.laravel-meta.outputs.tags }}
          labels: ${{ steps.laravel-meta.outputs.labels }}
